apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'user-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['user-service:3000']
      - job_name: 'booking-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['booking-service:3000']
      - job_name: 'hotel-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['hotel-service:3000']
      - job_name: 'rating-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['rating-service:3000']
      - job_name: 'payment-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['payment-service:3000']